import { DM_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Photosnap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <Navbar />
      <body className={inter.className} >
        {children}
        </body>
    </html>
  )
}
