import { DM_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Photosnap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">  
      <body className={inter.className} >
      <Navbar />
      <main>
      {children}
      </main>
      <Footer />
        </body>
    </html>
  )
}
